apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployement
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
      - name: nginx
        image: 978819838137.dkr.ecr.ap-northeast-1.amazonaws.com/jeevi:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
          - name: test
